const fs = require('fs');
const path = require('path');

const moreProducts = `
      // SPORTS
      { name: 'Yonex Astrox 99 Play Badminton Racquet', description: 'Head-heavy racquet designed for explosive smashes and fast-paced games.', price: 2999, originalPrice: 4290, category: sports._id, brand: 'Yonex', images: [{ url: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=600' }], stock: 65, isFeatured: true, rating: 4.5, numReviews: 890, sold: 2500, tags: ['sports', 'badminton', 'yonex'] },
      { name: 'Nivia Storm Football - Size 5', description: 'Rubber outer material with hand-stitched construction. Deflated for safe shipping.', price: 450, originalPrice: 650, category: sports._id, brand: 'Nivia', images: [{ url: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600' }], stock: 120, isFeatured: false, rating: 4.3, numReviews: 2100, sold: 8500, tags: ['sports', 'football'] },
      { name: 'Cosco Light Weight Tennis Ball (Pack of 6)', description: 'Ideal for cricket or casual tennis. High bounce and durable felt.', price: 399, originalPrice: 450, category: sports._id, brand: 'Cosco', images: [{ url: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=600' }], stock: 300, isFeatured: false, rating: 4.4, numReviews: 5400, sold: 21000, tags: ['sports', 'tennis', 'cricket'] },
      { name: 'Adidas Real Madrid Home Jersey 23/24', description: 'Official Real Madrid home jersey made with moisture-wicking AEROREADY fabric.', price: 4999, originalPrice: 4999, category: sports._id, brand: 'Adidas', images: [{ url: 'https://images.unsplash.com/photo-1517438476312-10d79c077509?w=600' }], stock: 40, isFeatured: true, rating: 4.8, numReviews: 320, sold: 980, tags: ['sports', 'jersey', 'football', 'adidas'] },
      { name: 'Puma One 8 Virat Kohli Cricket Shoes', description: 'Engineered for performance with spike sole for excellent grip on the pitch.', price: 3499, originalPrice: 5999, category: sports._id, brand: 'Puma', images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600' }], stock: 55, isFeatured: false, rating: 4.6, numReviews: 430, sold: 1200, tags: ['sports', 'shoes', 'cricket', 'puma'] },

      // MORE ELECTRONICS
      { name: 'Samsung 55" 4K Ultra HD Smart QLED TV', description: 'Quantum HDR, 100% Color Volume with Quantum Dot, and AirSlim design.', price: 64990, originalPrice: 99900, category: electronics._id, brand: 'Samsung', images: [{ url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600' }], stock: 25, isFeatured: true, rating: 4.7, numReviews: 1240, sold: 3200, tags: ['electronics', 'tv', 'television', 'samsung'] },
      { name: 'LG 65" 4K OLED evo Smart TV', description: 'Self-lit OLED pixels, a9 Gen5 AI Processor 4K, and Dolby Vision IQ.', price: 154990, originalPrice: 249990, category: electronics._id, brand: 'LG', images: [{ url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600' }], stock: 10, isFeatured: true, rating: 4.9, numReviews: 340, sold: 850, tags: ['electronics', 'tv', 'oled', 'lg'] },
      { name: 'Sony PlayStation 5 Console', description: 'Experience lightning-fast loading, deeper immersion with haptic feedback, and an all-new generation of incredible PlayStation games.', price: 44990, originalPrice: 54990, category: electronics._id, brand: 'Sony', images: [{ url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600' }], stock: 40, isFeatured: true, rating: 4.9, numReviews: 5400, sold: 15000, tags: ['gaming', 'console', 'ps5', 'sony'] },
      { name: 'Microsoft Xbox Series X', description: 'The fastest, most powerful Xbox ever. True 4K gaming, up to 120 FPS.', price: 49990, originalPrice: 55990, category: electronics._id, brand: 'Microsoft', images: [{ url: 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?w=600' }], stock: 35, isFeatured: false, rating: 4.8, numReviews: 3200, sold: 8900, tags: ['gaming', 'console', 'xbox'] },
      { name: 'Logitech G Pro X Superlight Mouse', description: 'Ultra-lightweight wireless gaming mouse designed with pro gamers. Sub-63 gram weight.', price: 12995, originalPrice: 13995, category: electronics._id, brand: 'Logitech', images: [{ url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600' }], stock: 65, isFeatured: true, rating: 4.8, numReviews: 1240, sold: 3400, tags: ['gaming', 'mouse', 'logitech'] },

      // MORE BEAUTY & PERSONAL CARE
      { name: 'Philips Multi Grooming Kit MG3710/65', description: '9-in-1 face, hair and body trimmer. Self-sharpening steel blades and 60 mins run time.', price: 1699, originalPrice: 1995, category: beauty._id, brand: 'Philips', images: [{ url: 'https://images.unsplash.com/photo-1621607512214-68297480165e?w=600' }], stock: 150, isFeatured: false, rating: 4.3, numReviews: 8900, sold: 25000, tags: ['beauty', 'trimmer', 'philips'] },
      { name: 'Dyson Airwrap Multi-Styler', description: 'Curl, shape, and hide flyaways with the Coanda effect - without extreme heat.', price: 49900, originalPrice: 49900, category: beauty._id, brand: 'Dyson', images: [{ url: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?w=600' }], stock: 25, isFeatured: true, rating: 4.8, numReviews: 560, sold: 1200, tags: ['beauty', 'hair', 'dyson'] },
      { name: 'Nivea Soft Light Moisturizing Cream', description: 'Light, non-greasy moisturizing cream with Vitamin E and Jojoba Oil for highly effective, refreshing moisture.', price: 250, originalPrice: 349, category: beauty._id, brand: 'Nivea', images: [{ url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600' }], stock: 400, isFeatured: false, rating: 4.5, numReviews: 23000, sold: 65000, tags: ['beauty', 'skincare', 'nivea'] },
      { name: 'M.A.C Retro Matte Lipstick - Ruby Woo', description: 'The iconic matte lipstick that made M.A.C famous. Long-wearing, fiercely red.', price: 1950, originalPrice: 1950, category: beauty._id, brand: 'M.A.C', images: [{ url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600' }], stock: 95, isFeatured: true, rating: 4.7, numReviews: 4500, sold: 12000, tags: ['beauty', 'makeup', 'lipstick', 'mac'] },
      
      // GROCERY & HOME ESSENTIALS
      { name: 'Tata Tea Premium (1 kg)', description: 'Desh ki Chai. Carefully crafted blend for the perfect cup of strong tea.', price: 440, originalPrice: 520, category: homeGarden._id, brand: 'Tata', images: [{ url: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=600' }], stock: 500, isFeatured: false, rating: 4.5, numReviews: 32000, sold: 85000, tags: ['grocery', 'tea'] },
      { name: 'India Gate Basmati Rice (5 kg)', description: 'Premium aged basmati rice perfect for biryani and everyday cooking.', price: 899, originalPrice: 1050, category: homeGarden._id, brand: 'India Gate', images: [{ url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600' }], stock: 250, isFeatured: false, rating: 4.6, numReviews: 12000, sold: 34000, tags: ['grocery', 'rice'] },
      { name: 'Aashirvaad Select Premium Sharbati Atta (5 kg)', description: 'Made from the finest Sharbati wheat grains handpicked from Sehore, MP.', price: 299, originalPrice: 345, category: homeGarden._id, brand: 'Aashirvaad', images: [{ url: 'https://images.unsplash.com/photo-1627485937980-221c88ce04be?w=600' }], stock: 400, isFeatured: false, rating: 4.7, numReviews: 18000, sold: 45000, tags: ['grocery', 'atta'] },
      { name: 'Fortune Sunlite Refined Sunflower Oil (5 L)', description: 'Light, healthy and easy to digest. Fortified with vitamins.', price: 799, originalPrice: 950, category: homeGarden._id, brand: 'Fortune', images: [{ url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600' }], stock: 350, isFeatured: false, rating: 4.4, numReviews: 21000, sold: 56000, tags: ['grocery', 'oil'] },

      // MORE FASHION
      { name: 'Fastrack Reflex Play Smartwatch', description: 'AMOLED display smartwatch with animated watch faces, blood pressure monitoring.', price: 4995, originalPrice: 7995, category: electronics._id, brand: 'Fastrack', images: [{ url: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600' }], stock: 120, isFeatured: false, rating: 4.3, numReviews: 1200, sold: 3400, tags: ['watch', 'smartwatch', 'fastrack'] },
      { name: 'Titan Edge Ultra Slim Men\\'s Watch', description: 'The slimmest watch in the universe. Sapphire crystal glass and premium leather strap.', price: 12495, originalPrice: 12495, category: electronics._id, brand: 'Titan', images: [{ url: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600' }], stock: 45, isFeatured: true, rating: 4.8, numReviews: 670, sold: 1800, tags: ['watch', 'analog', 'titan', 'premium'] },
      { name: 'Woodland Men\\'s Leather Boots', description: 'Tough, durable, and comfortable leather boots designed for adventure.', price: 3499, originalPrice: 4295, category: clothing._id, brand: 'Woodland', images: [{ url: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600' }], stock: 85, isFeatured: false, rating: 4.5, numReviews: 3200, sold: 9800, tags: ['shoes', 'boots', 'mens', 'woodland'] },
      { name: 'Red Tape Men\\'s Casual Sneakers', description: 'Lightweight and stylish casual sneakers with memory foam insole.', price: 1499, originalPrice: 4999, category: clothing._id, brand: 'Red Tape', images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600' }], stock: 200, isFeatured: false, rating: 4.2, numReviews: 5400, sold: 15000, tags: ['shoes', 'sneakers', 'mens', 'budget'] }
`;

const seedFilePath = path.join(__dirname, 'seed.js');
let seedContent = fs.readFileSync(seedFilePath, 'utf8');

// Inject before "    ];" of the products array
const insertIndex = seedContent.lastIndexOf('    ];');
if (insertIndex !== -1) {
  const newContent = seedContent.slice(0, insertIndex) + moreProducts.slice(1, -2) + ',\\n' + seedContent.slice(insertIndex);
  
  fs.writeFileSync(seedFilePath, newContent, 'utf8');
  console.log('Successfully injected 22 more realistic products into seed.js');
} else {
  console.error('Could not find injection point in seed.js');
}
